name: CI

on: push

jobs:
  phplint:
    name: PHP Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: PHP Lint 8.4
        uses: dbfx/github-phplint/8.4@master
        with:
          folder-to-exclude: "! -path \"./vendor/*\""

  compposer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Composer validate
        run: composer validate --strict

  check-namespaces:
    name: Check namespaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Composer install
        uses: ramsey/composer-install@v3

      - name: Check namespaces
        run: composer dump-autoload --optimize --strict-psr
  phpstan84:
    name: PHPStan 8.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Composer install
        run: composer install

      - name: PHPStan
        run: composer stan